In [81]:
import os.path
import string
from os import listdir
import numpy as np

#Folder containing the labeled snippet subfolders for training the classifier
snippetFolder = "/home/abc/ADM/Train_Data"

#folder containing unlabeled snippets
testSnippetFolder = "/home/abc/ADM/Test_Data"

folder_list = [f for f in listdir(snippetFolder)]

puncs = string.punctuation

X = []
Y = []
for folder in folder_list:
    files_list = [f for f in listdir(snippetFolder + "/" + folder)]
    for file in files_list:
        filePath = snippetFolder + "/" + folder + "/" + file
        f = open(filePath,'r',encoding='utf-8')
        data = f.readlines()
        textSnippet = ''.join(data)
        textSnippet = textSnippet.replace("\n","")
        for p in puncs:
            if p in textSnippet:
                textSnippet = textSnippet.replace(p,"")
        X.append(textSnippet)
        Y.append(folder)
    
print(len(X))
print(len(Y))

#from sklearn.feature_extraction import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.model_selection import cross_val_score

#tfidf = TfidfVectorizer(input='content',encoding='utf-8',decode_error='ignore',strip_accents='ascii',ngram_range=(2,2),stop_words='english',max_df=80,min_df=6,max_features=None,norm='l1')
tfidf = TfidfVectorizer(input='content',encoding='utf-8',decode_error='ignore',strip_accents='ascii',ngram_range=(2,2),stop_words='english',max_features=60,norm='l1')
train = tfidf.fit_transform(X,Y)
#print(tfidf.get_feature_names())
#print("\nWords Removed : \n",tfidf.stop_words_)
#print(tfidf.build_analyzer())

cv=5


!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
164
164


In [82]:
#Logistic Regression Classifier
from sklearn.linear_model import LogisticRegression

clf_lr = LogisticRegression()
acc = cross_val_score(clf_lr,train,Y,scoring="accuracy",cv=cv)
print(acc)
print(np.mean(acc))

clf_lr.fit(train,Y)

[ 0.54285714  0.51515152  0.63636364  0.5625      0.61290323]
0.573955104036


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [83]:
#Support Vector Machine Classifier
from sklearn.svm import SVC,LinearSVC

clf_svc = SVC(C=0.1,random_state=123)
acc = cross_val_score(clf_svc,train,Y,scoring="accuracy",cv=cv)
print(acc)
print(np.mean(acc))

clf_svc.fit(train,Y)

clf_linear_svc = LinearSVC(C=0.1,random_state=123)
acc = cross_val_score(clf_linear_svc,train,Y,scoring="accuracy",cv=cv)
print(acc)
print(np.mean(acc))

clf_linear_svc.fit(train,Y)

[ 0.34285714  0.36363636  0.36363636  0.34375     0.35483871]
0.353743715961
[ 0.51428571  0.51515152  0.63636364  0.53125     0.58064516]
0.555539205418


LinearSVC(C=0.1, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=123, tol=0.0001,
     verbose=0)

In [84]:
#Random Forest Classifier


In [85]:
#Neural Network Classifier
from sklearn.neural_network import MLPClassifier
clf_NN = MLPClassifier(hidden_layer_sizes=(5,10),activation="logistic",solver="lbfgs",alpha=0.01,learning_rate="adaptive",max_iter=100,shuffle=True,early_stopping=True,random_state=123)
acc = cross_val_score(clf_NN,train,Y,scoring="accuracy",cv=cv)
print(acc)
print(np.mean(acc))

clf_NN.fit(train,Y)

[ 0.74285714  0.66666667  0.63636364  0.6875      0.67741935]
0.682161360145


MLPClassifier(activation='logistic', alpha=0.01, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=True, epsilon=1e-08,
       hidden_layer_sizes=(5, 10), learning_rate='adaptive',
       learning_rate_init=0.001, max_iter=100, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=123,
       shuffle=True, solver='lbfgs', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [86]:
#Clustering Techniques

In [87]:
testData = []
file_list = [f for f in listdir(testSnippetFolder)]

for file in file_list:
    filePath = testSnippetFolder + "/" + file
    f = open(filePath,'r',encoding='utf-8')
    data = f.readlines()
    textSnippet = ''.join(data)
    textSnippet = textSnippet.replace("\n","")
    for p in puncs:
        if p in textSnippet:
            textSnippet = textSnippet.replace(p,"")

    testData.append(textSnippet)
    
#tfidf_test = TfidfVectorizer(input='content',encoding='utf-8',decode_error='ignore',strip_accents='ascii',ngram_range=(2,2),stop_words='english',max_features=None,norm='l1')
test = tfidf.transform(testData)


In [88]:
#print(clf_lr.coef_)

Y_test_lr = clf_lr.predict(test)

Y_test_svc = clf_svc.predict(test)

Y_test_linear_svc = clf_linear_svc.predict(test)

Y_test_nn = clf_NN.predict(test)

print(len(file_list))
print(len(Y_test_lr))

l = len(file_list)
final_list = []
for i in range(l):
    final_list.append((file_list[i],Y_test_nn[i]))
print(final_list)  

35
35
[('3102088__1.txt', 'CS_Sullivan'), ('hvd.32044039365119__10.txt', 'CS_Armour'), ('468039__33.txt', 'CS_Tallmadge'), ('nnc1.cu04264290__1.txt', 'CS_Armour'), ('1425278__2.txt', 'CS_Tallmadge'), ('mdp.39015031294864__1.txt', 'CS_Tallmadge'), ('774830__1.txt', 'CS_Tallmadge'), ('hvd.32044039365119__2.txt', 'CS_civics'), ('njp.32101059234532__1.txt', 'CS_Armour'), ('1997_1047944__2.txt', 'CS_Sullivan'), ('25505243__2.txt', 'CS_Armour'), ('nnc1.ar53666712__1.txt', 'CS_Sullivan'), ('nyp.33433071108827__4.txt', 'CS_Tallmadge'), ('1991_990613__2.txt', 'CS_Sullivan'), ('1959_1424016__1.txt', 'CS_Tallmadge'), ('773093__1.txt', 'CS_Armour'), ('mdp.39015082311138__1.txt', 'CS_Tallmadge'), ('hvd.32044039365119__9.txt', 'CS_Armour'), ('1424869__6.txt', 'CS_Tallmadge'), ('mdp.39015059791270__1.txt', 'CS_Tallmadge'), ('4117456__1.txt', 'CS_Armour'), ('ncs1.ark+=13960=t45q5jt4w__1.txt', 'CS_Tallmadge'), ('nyp.33433060463365__1.txt', 'CS_Tallmadge'), ('4102638__1.txt', 'CS_Armour'), ('mdp.3901504

In [89]:
#find out the top features used by each classifier