In [5]:
import os.path
import string
from os import listdir
snippetFolder = "/home/abc/ADM/Train_Data"
testSnippetFolder = "/home/abc/ADM/Test_Data"
folder_list = [f for f in listdir(snippetFolder)]
#print(folder_list)

puncs = string.punctuation
print(puncs)

X = []
Y = []
for folder in folder_list:
    #print(folder)
    files_list = [f for f in listdir(snippetFolder + "/" + folder)]
    #print(files_list)
    #print("\n")
    for file in files_list:
        filePath = snippetFolder + "/" + folder + "/" + file
        #print("File Path : ", filePath)
        f = open(filePath,'r',encoding='utf-8')
        data = f.readlines()
        #print("Data : ", data)
        #for d in data:
        #    d.replace("\n","")
        textSnippet = ''.join(data)
        #print("Text : ",textSnippet)
        textSnippet = textSnippet.replace("\n","")
        #textSnippet = textSnippet.replace('"',"")
        
        for p in puncs:
            #print(p)
            if p in textSnippet:
                #print("Replacing : ",p)
                textSnippet = textSnippet.replace(p,"")
        
        #print("Text : ",textSnippet)
        #print("\n")
        X.append(textSnippet)
        Y.append(folder)
    
print(len(X))
print(len(Y))
#print(X[:10])

#from sklearn.feature_extraction import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.model_selection import cross_val_score

tfidf = TfidfVectorizer(input='content',encoding='utf-8',decode_error='ignore',strip_accents='ascii',ngram_range=(2,2),stop_words='english',max_df=80,min_df=6,max_features=None,norm='l1')
train = tfidf.fit_transform(X,Y)
#print(tfidf.get_feature_names())
#print("\nWords Removed : \n",tfidf.stop_words_)
#print(tfidf.build_analyzer())

cv=5


!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
114
114


In [17]:
#Logistic Regression Classifier
from sklearn.linear_model import LogisticRegression

clf_lr = LogisticRegression()
acc = cross_val_score(clf_lr,train,Y,scoring="accuracy",cv=cv)
print(acc)
print(np.mean(acc))

[ 0.54166667  0.60869565  0.69565217  0.60869565  0.57142857]
0.605227743271


In [18]:
#Support Vector Machine Classifier
from sklearn.svm import SVC,LinearSVC

clf_svc = SVC(C=0.1,random_state=123)
acc = cross_val_score(clf_svc,train,Y,scoring="accuracy",cv=cv)
print(acc)
print(np.mean(acc))

clf_svc = LinearSVC(C=0.1,random_state=123)
acc = cross_val_score(clf_svc,train,Y,scoring="accuracy",cv=cv)
print(acc)
print(np.mean(acc))

[ 0.375       0.39130435  0.39130435  0.39130435  0.38095238]
0.385973084886
[ 0.58333333  0.60869565  0.69565217  0.60869565  0.57142857]
0.613561076605


In [58]:
#Random Forest Classifier


In [15]:
#Neural Network Classifier
from sklearn.neural_network import MLPClassifier
clf_NN = MLPClassifier(hidden_layer_sizes=(5,10),activation="logistic",solver="lbfgs",alpha=0.01,learning_rate="adaptive",max_iter=100,shuffle=True,early_stopping=True,random_state=123)
acc = cross_val_score(clf_NN,train,Y,scoring="accuracy",cv=cv)
print(acc)
print(np.mean(acc))

[ 0.58333333  0.60869565  0.69565217  0.60869565  0.61904762]
0.623084886128


In [60]:
#Clustering Techniques

In [1]:
testData = []
file_list = [f for f in listdir(testSnippetFolder)]
#for file in file_list:
    #print(folder)
    #files_list = [f for f in listdir(snippetFolder + "/" + folder)]
    #print(files_list)
    #print("\n")
for file in file_list:
    filePath = testSnippetFolder + "/" + file
    #print("File Path : ", filePath)
    f = open(filePath,'r',encoding='utf-8')
    data = f.readlines()
    #print("Data : ", data)
    #for d in data:
    #    d.replace("\n","")
    textSnippet = ''.join(data)
    #print("Text : ",textSnippet)
    textSnippet = textSnippet.replace("\n","")
    #textSnippet = textSnippet.replace('"',"")

    for p in puncs:
        #print(p)
        if p in textSnippet:
            #print("Replacing : ",p)
            textSnippet = textSnippet.replace(p,"")

    #print("Text : ",textSnippet)
    #print("\n")
    testData.append(textSnippet)


NameError: name 'listdir' is not defined

In [2]:
#find out the top features used by each classifier